#!/bin/bash
get_data () {
	date '+%A %W %Y %X' | tee logFile1.txt
	w | tee logFile2.txt
	#uptime | tee logFile3.txt this is the same as the first line of the "w" command
	cat logFile1.txt logFile2.txt >> logFile.txt
	rm logFile1.txt logFile2.txt
}

#auto overwrite the existing log file.
pipe_data () {
	echo "$(date)" > logFile.txt
	echo "$(w)" >> logFile.txt
	echo "$(uptime)" >> logFile.txt
}

get_data

#pipe_data


