#!/bin/bash

echo "Loops 100 times, printing the numbers"
a=0

#checks if a is less than the given value
for number1 in {1..10} 
do
	for number2 in {1..10}
	do
		((a++))
		if [ $a -le 10 ]
		then
			echo -n "$a   "
		elif [ $a -le 100 ] 
		then 
			echo -n "$a  "
		else 
			echo -n "$a "
		fi
	done
	echo ""
done

echo "done all loops"
